/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  // Dark mode is driven by the data-theme attribute (token swap on :root),
  // not the OS media query — so `dark:` utilities also key off it.
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        /* ---- Design-system semantic tokens (CSS-variable backed) ----
           Every value reads a var() so dark mode is a pure token swap.
           These are additive; the navy/maroon/sunburst scales below are
           kept intact so existing utilities never change. */
        plane: 'var(--plane)',
        surface: {
          DEFAULT: 'var(--surface)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
        },
        ink: {
          DEFAULT: 'var(--text-1)',
          2: 'var(--text-2)',
          3: 'var(--text-3)',
          inverse: 'var(--text-inverse)',
        },
        line: {
          DEFAULT: 'var(--line)',
          2: 'var(--line-2)',
          strong: 'var(--line-strong)',
        },
        rail: {
          DEFAULT: 'var(--rail)',
          ink: 'var(--rail-ink)',
          'ink-2': 'var(--rail-ink-2)',
          'ink-3': 'var(--rail-ink-3)',
          line: 'var(--rail-line)',
          active: 'var(--rail-active)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          ink: 'var(--accent-ink)',
          wash: 'var(--accent-wash)',
          'wash-2': 'var(--accent-wash-2)',
          ring: 'var(--accent-ring)',
        },
        viz: {
          1: 'var(--viz-1)',
          2: 'var(--viz-2)',
          3: 'var(--viz-3)',
          4: 'var(--viz-4)',
          series: 'var(--viz-series)',
          'series-soft': 'var(--viz-series-soft)',
          grid: 'var(--viz-grid)',
          axis: 'var(--viz-axis)',
          muted: 'var(--viz-muted)',
        },
        st: {
          applied: 'var(--st-applied)',
          'applied-bg': 'var(--st-applied-bg)',
          'applied-fg': 'var(--st-applied-fg)',
          pending: 'var(--st-pending)',
          'pending-bg': 'var(--st-pending-bg)',
          'pending-fg': 'var(--st-pending-fg)',
          approved: 'var(--st-approved)',
          'approved-bg': 'var(--st-approved-bg)',
          'approved-fg': 'var(--st-approved-fg)',
          cancelled: 'var(--st-cancelled)',
          'cancelled-bg': 'var(--st-cancelled-bg)',
          'cancelled-fg': 'var(--st-cancelled-fg)',
          paid: 'var(--st-paid)',
          'paid-bg': 'var(--st-paid-bg)',
          'paid-fg': 'var(--st-paid-fg)',
        },
        role: {
          developer: 'var(--role-developer)',
          'developer-bg': 'var(--role-developer-bg)',
          'developer-fg': 'var(--role-developer-fg)',
          'developer-ring': 'var(--role-developer-ring)',
          designer: 'var(--role-designer)',
          'designer-bg': 'var(--role-designer-bg)',
          'designer-fg': 'var(--role-designer-fg)',
          'designer-ring': 'var(--role-designer-ring)',
          cyber: 'var(--role-cyber)',
          'cyber-bg': 'var(--role-cyber-bg)',
          'cyber-fg': 'var(--role-cyber-fg)',
          'cyber-ring': 'var(--role-cyber-ring)',
        },
        navy: {
          50: '#f4f6fb',
          100: '#e7ebf5',
          200: '#c7d0e6',
          300: '#97a6cc',
          400: '#5f74a4',
          500: '#374d7d',
          600: '#233563',
          700: '#18274c',
          800: '#101d3c',
          900: '#0a1733',
          DEFAULT: '#0a1733',
        },
        maroon: {
          50: '#fbf0f7',
          100: '#f6dcec',
          200: '#ecb8d7',
          300: '#dd85b7',
          400: '#c24f92',
          500: '#98266c',
          600: '#5e0743',
          700: '#4d0537',
          800: '#3a042a',
          900: '#28031d',
          DEFAULT: '#5e0743',
        },
        sunburst: {
          50: '#fff5e9',
          100: '#ffe6c9',
          200: '#ffca8e',
          300: '#ffab51',
          400: '#ff8f26',
          500: '#ff7300',
          600: '#e65f00',
          700: '#bf4c00',
          800: '#983d05',
          900: '#7c3408',
          DEFAULT: '#ff7300',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        display: [
          'Iowan Old Style',
          'Palatino Linotype',
          'Palatino',
          'Georgia',
          'serif',
        ],
      },
      borderRadius: {
        xl: '0.85rem',
        '2xl': '1.1rem',
        /* Design-system radii (additive) */
        chip: 'var(--radius-chip)',
        card: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        card: '0 1px 2px rgba(10, 23, 51, 0.06), 0 6px 20px -12px rgba(10, 23, 51, 0.25)',
        lift: '0 6px 16px -6px rgba(10, 23, 51, 0.22), 0 18px 40px -20px rgba(10, 23, 51, 0.35)',
        modal: '0 24px 60px -18px rgba(10, 23, 51, 0.45)',
        pop: '0 10px 32px -8px rgba(10, 23, 51, 0.28)',
        /* Design-system elevation tokens (additive, CSS-variable backed) */
        e1: 'var(--shadow-sm)',
        e2: 'var(--shadow-md)',
        e3: 'var(--shadow-lg)',
        e4: 'var(--shadow-xl)',
        accent: 'var(--shadow-accent)',
      },
      keyframes: {
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-6px)' },
          '40%': { transform: 'translateX(6px)' },
          '60%': { transform: 'translateX(-4px)' },
          '80%': { transform: 'translateX(4px)' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        shake: 'shake 0.45s ease-in-out',
        'fade-in': 'fade-in 0.14s ease-out',
      },
    },
  },
  plugins: [],
}
